language: csharp
mono: none
dotnet: 2.0.0

matrix:
  include:
    - os: linux
      dist: trusty     
    - os: osx
    
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y tor; else brew install tor; fi
  - tor SOCKSPort 9050 ControlPort 9051 HashedControlPassword 16:0978DBAF70EEB5C46063F3F6FD8CBC7A86DF70D2206916C1E2AE29EAF6

script:
  - cd src/DotNetTor.Tests
  - dotnet test
