language: csharp
mono: none
dotnet: 2.0.0

matrix:
  include:
    - os: linux
      dist: trusty     
    - os: osx
    
before_install:
  - sudo apt-get install -y tor

script:
  - cd DotNetTor.Tests
  - dotnet test
