language: csharp
mono: none
dotnet: 2.0.0

matrix:
  include:
    - os: linux
      dist: trusty     
    - os: osx
    
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y tor; else brew install tor; fi

script:
  - cd DotNetTor.Tests
  - dotnet test
